import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },

  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 30,
  },
  loadingIcon: {
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingIndicator: { marginTop: 18 },
  loadingText: { marginTop: 10, fontSize: 13 },

  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 120,
  },

  /* WELCOME */
  welcomeSection: { marginBottom: 22 },
  welcomeTitle: { fontSize: 22, fontWeight: "700", marginBottom: 5 },
  welcomeSubtitle: { fontSize: 13, lineHeight: 19 },

  clinicBadge: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  clinicIcon: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,84,130,0.10)",
    marginRight: 9,
  },
  clinicInfo: { maxWidth: 220 },
  clinicLabel: { fontSize: 11, marginBottom: 1 },
  clinicName: { fontSize: 13 },

  /* SECTIONS */
  section: { marginBottom: 23 },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 9,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700" },
  sectionAction: { fontSize: 12 },

  /* BALANCE */
  balanceCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  balanceIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: "rgba(245,158,11,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  balanceLabel: { fontSize: 12, marginBottom: 2 },
  balanceAmount: { fontSize: 20, color: "#F59E0B" },
  payButton: {
    height: 38,
    borderRadius: 10,
    backgroundColor: "#005482",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  payButtonText: { fontSize: 12, color: "#FFFFFF" },

  /* EMPTY */
  emptyCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 18,
    alignItems: "center",
  },
  emptyIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,84,130,0.10)",
  },
  emptyTitle: { fontSize: 14, marginTop: 10, textAlign: "center" },
  emptyDescription: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
    textAlign: "center",
    maxWidth: 270,
  },
  emptyButton: {
    height: 36,
    borderRadius: 10,
    backgroundColor: "#005482",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    marginTop: 13,
  },
  emptyButtonText: { fontSize: 12, color: "#FFFFFF" },

  /* APPOINTMENT */
  appointmentCard: { borderWidth: 1, borderRadius: 18, padding: 14 },
  appointmentTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  appointmentDateBox: { flexDirection: "row", alignItems: "center", flex: 1 },
  appointmentDateContent: { marginLeft: 10, flex: 1 },
  appointmentDate: { fontSize: 14, fontWeight: "700" },
  appointmentTime: { fontSize: 12, marginTop: 2 },
  confirmedBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: "rgba(16,185,129,0.10)",
  },
  confirmedDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#10B981",
    marginRight: 5,
  },
  confirmedText: { fontSize: 11, color: "#059669" },
  divider: { height: StyleSheet.hairlineWidth, marginVertical: 13 },

  infoRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  infoIcon: {
    width: 30,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 5,
  },
  infoContent: { flex: 1 },
  infoLabel: { fontSize: 11, marginBottom: 1 },
  infoValue: { fontSize: 13 },

  appointmentActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 5,
  },
  outlineButton: {
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 13,
  },
  outlineButtonText: { fontSize: 12 },
  primaryButton: {
    height: 38,
    borderRadius: 10,
    backgroundColor: "#005482",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 13,
    gap: 6,
  },
  primaryButtonText: { fontSize: 12, color: "#FFFFFF" },

  /* TREATMENT */
  treatmentCard: { borderWidth: 1, borderRadius: 18, padding: 15 },
  treatmentHeader: { flexDirection: "row", alignItems: "center" },
  treatmentIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,84,130,0.10)",
  },
  treatmentTitleContainer: { flex: 1, marginLeft: 11 },
  treatmentName: { fontSize: 14 },
  treatmentSubtitle: { fontSize: 11, marginTop: 2 },
  progressNumber: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(0,84,130,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  progressNumberText: { fontSize: 11, color: "#005482" },
  progressTrack: {
    height: 7,
    borderRadius: 999,
    marginTop: 15,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: 999, backgroundColor: "#005482" },
  summaryCard: { borderWidth: 1, borderRadius: 18, padding: 15 },
  summaryHeader: { flexDirection: "row", alignItems: "center" },
  summaryIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryHeaderText: { flex: 1, marginLeft: 11 },
  summaryTitle: { fontSize: 14 },
  summarySubtitle: { fontSize: 11, marginTop: 2 },
  summaryValue: { fontSize: 13, color: "#005482" },
  pendingProcedure: { flexDirection: "row", alignItems: "center", marginTop: 13, gap: 7 },
  pendingProcedureText: { flex: 1, fontSize: 11 },
  paymentCard: { borderWidth: 1, borderRadius: 18, padding: 15 },
  paymentMain: { flexDirection: "row", alignItems: "center" },
  paymentIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: "rgba(245,158,11,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  paymentMainText: { marginLeft: 11 },
  paymentAmount: { fontSize: 20, color: "#F59E0B", marginTop: 1 },
  paymentDivider: { height: StyleSheet.hairlineWidth, marginVertical: 13 },
  paymentDetails: { flexDirection: "row", justifyContent: "space-between" },
  paymentDetailLabel: { fontSize: 11 },
  paymentDetailValue: { fontSize: 13, marginTop: 2 },
  nextTreatment: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 13,
    gap: 8,
  },
  nextTreatmentLabel: { fontSize: 11, marginBottom: 2 },
  nextTreatmentValue: { fontSize: 13 },
  nextTreatmentDate: { fontSize: 11, color: "#005482" },

  /* PROMOTION */
  promotionCard: {
    minHeight: 155,
    borderRadius: 18,
    backgroundColor: "#005482",
    overflow: "hidden",
    position: "relative",
  },
  promotionGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255,255,255,0.08)",
    right: -55,
    top: -70,
  },
  promotionContent: { padding: 17, paddingRight: 60 },
  promotionTag: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  promotionTagText: { fontSize: 10, color: "#005482" },
  promotionTitle: { fontSize: 18, color: "#FFFFFF", marginTop: 12 },
  promotionDiscount: {
    alignSelf: "flex-start",
    marginTop: 7,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  promotionDiscountText: { fontSize: 12, color: "#FFFFFF" },
  promotionDescription: {
    fontSize: 12,
    lineHeight: 17,
    color: "rgba(255,255,255,0.82)",
    marginTop: 9,
  },
  promotionValidity: {
    fontSize: 11,
    color: "rgba(255,255,255,0.65)",
    marginTop: 7,
  },
  promotionArrow: {
    position: "absolute",
    right: 16,
    bottom: 16,
    width: 35,
    height: 35,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },

  /* LAST ATTENTION */
  lastAttentionCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  lastAttentionIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: "rgba(16,185,129,0.10)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  lastAttentionContent: { flex: 1 },
  lastAttentionTitle: { fontSize: 13 },
  lastAttentionDate: { fontSize: 11, marginTop: 3 },
  lastAttentionDentist: { fontSize: 11, marginTop: 2 },

  /* QUICK ACTIONS */
  quickGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  quickItem: {
    width: "48%",
    minHeight: 72,
    borderWidth: 1,
    borderRadius: 15,
    paddingHorizontal: 11,
    paddingVertical: 10,
    justifyContent: "center",
    position: "relative",
  },
  quickIcon: { marginBottom: 7 },
  quickLabel: { fontSize: 12 },
  quickArrow: { position: "absolute", right: 10, top: 11 },

  bottomSpace: { height: 20 },
});
